# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177e72e80a3a4dbb01f489bd2fc4a414c62b9ed797ec9adf509399c1acb70f5235d8f14f82062e90156f6473e6c465cf7f58337243b9bccdbd1e8d7c52c30a2a

test:
  secret_key_base: 803151cc13b387cf5263719e4450479795f0e18aa022708ae5b95e88f17d7977eb3e995dec1b0d18336b11e13c607f5e6d2d9a7d8e8a175fb16c4d14608a4c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
